# Generated by Django 5.0.6 on 2024-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_schoolcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
