# Generated by Django 5.0.6 on 2024-06-29 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_newsheadline_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsheadline',
            name='id',
        ),
        migrations.AddField(
            model_name='newsheadline',
            name='news_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
