# Generated by Django 5.0.6 on 2024-07-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_newsheadline_id'),
        ('backend', '0022_remove_newsheadline_news_id_newsheadline_id'),
    ]

    operations = [
    ]
