# Generated by Django 5.0.6 on 2024-07-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_merge_20240708_0152'),
        ('backend', '0026_alter_chatmessage_user'),
    ]

    operations = [
    ]
