# Generated by Django 5.0.6 on 2024-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_videocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
