# Generated by Django 5.0.6 on 2024-07-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_chatmessage_user_chatmessage_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
