# Generated by Django 5.0.6 on 2024-07-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
