# Generated by Django 5.0.6 on 2024-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
