# Generated by Django 5.0.6 on 2024-07-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
    ]
