# Generated by Django 5.0.6 on 2024-08-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_videocomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivities',
            name='term',
            field=models.CharField(blank=True, choices=[('Events', 'Events'), ('Letters', 'Letters'), ('Speeches', 'Speeches')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='classes',
            field=models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Jss 1', 'Jss 1'), ('Jss 2', 'Jss 2'), ('Jss 3', 'Jss 3'), ('Ss 1', 'Ss 1'), ('Ss 2', 'Ss 2'), ('Ss 3', 'Ss 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='classes',
            field=models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Jss 1', 'Jss 1'), ('Jss 2', 'Jss 2'), ('Jss 3', 'Jss 3'), ('Ss 1', 'Ss 1'), ('Ss 2', 'Ss 2'), ('Ss 3', 'Ss 3')], max_length=50),
        ),
    ]
