# Generated by Django 5.0.6 on 2024-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_schoolactivities_term_alter_examquestion_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
