# Generated by Django 5.0.6 on 2024-08-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_graduation_schoolpolicies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolactivities',
            old_name='term',
            new_name='activities',
        ),
    ]
