# Generated by Django 5.0.6 on 2024-08-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_newscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='video_id',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.newsheadline'),
        ),
    ]
